/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ol.helper;

import java.awt.Color;
import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author ilyin
 */
public class MainForm extends javax.swing.JFrame  {

    /**
     * Creates new form MainForm
     */
    
    
    String checkhost = "10.0.0.8";
    String linkstatustring = "НЕ ОПРДЕЛЕНО";
    private final static int SMTP_PORT = 25;
    private final static String MAIL_SERVER = "192.168.0.1";
    private final static String SENDER_EMAIL = "it@pressa66.ru";
    private final static String RECEIVER_EMAIL = "ilyin@pressa66.ru";
    private final static String EMAIL_MESSAGE = "Hi! This is a test email agent!";



    public MainForm()throws UnknownHostException, IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LinkStatusPanel = new javax.swing.JPanel();
        LinkStatus = new javax.swing.JLabel();
        sendemail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OL-HELPER");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        LinkStatus.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        LinkStatus.setText("UNKNOWN");

        javax.swing.GroupLayout LinkStatusPanelLayout = new javax.swing.GroupLayout(LinkStatusPanel);
        LinkStatusPanel.setLayout(LinkStatusPanelLayout);
        LinkStatusPanelLayout.setHorizontalGroup(
            LinkStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LinkStatusPanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(LinkStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(155, 155, 155))
        );
        LinkStatusPanelLayout.setVerticalGroup(
            LinkStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LinkStatusPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(LinkStatus)
                .addContainerGap())
        );

        sendemail.setBackground(new java.awt.Color(255, 153, 0));
        sendemail.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        sendemail.setText("Перезвоните мне!");
        sendemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendemailActionPerformed(evt);
            }
        });
        sendemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sendemailKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LinkStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(sendemail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LinkStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(sendemail)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      //  String linkstatustring = "НЕ ОПРДЕЛЕНО";
        LinkStatusPanel.setBackground(Color.yellow);
        LinkStatus.setText(linkstatustring);
        
        //InetAddress inet;
        try {
            InetAddress inet = InetAddress.getByName(checkhost);
            if (inet.isReachable(5000)){
                LinkStatusPanel.setBackground(Color.green);
                linkstatustring = "ONLINE";
            } else {
                LinkStatusPanel.setBackground(Color.red);
                linkstatustring = "OFFLINE";
                sendemail.setVisible(false);
                
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        LinkStatus.setText(linkstatustring);
    //  
   
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void sendemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sendemailKeyPressed
    
    }//GEN-LAST:event_sendemailKeyPressed

    private void sendemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendemailActionPerformed
        // TODO add your handling code here:
            linkstatustring = "SEND EMAIL";
            LinkStatus.setText(linkstatustring); 
     
  //           hoststatus = "do cmd";
    //    jLabel1.setText(hoststatus);
     //       try {
     //           Runtime rt = Runtime.getRuntime();
      //          Process pr = rt.exec("c:/java/test.cmd");
     //       } catch(Exception e) {
              // System.out.println(e.toString());
              //e.printStackTrace();
       //     }; 
            Socket socket = null;

         try
    {
        socket = new Socket(MAIL_SERVER, SMTP_PORT);
        InputStream is = socket.getInputStream();
        InputStreamReader isr = new InputStreamReader(is);
        BufferedReader br = new BufferedReader(isr);

        String response = br.readLine();
        if (!response.startsWith("220")) {
    //        throw new Exception("220 reply not received from server.");
        }

        OutputStream os = socket.getOutputStream();

        String command = "HELO\r\n";
        os.write(command.getBytes("US-ASCII"));
        response = br.readLine();
        if (!response.startsWith("250")) {
      //      throw new Exception("250 reply not received from server.");
        }
        command = "MAIL FROM: "+SENDER_EMAIL+"\r\n";
        os.write(command.getBytes("US-ASCII"));
        response = br.readLine();
        command = "RCPT TO: "+RECEIVER_EMAIL+"\r\n";
        os.write(command.getBytes("US-ASCII"));
        response = br.readLine();
        command = "DATA"+"\r\n";
        os.write(command.getBytes("US-ASCII"));
        response = br.readLine();
        command = EMAIL_MESSAGE+"\r\n";
        os.write(command.getBytes("US-ASCII"));
        command = "\r\n."+"\r\n";
        os.write(command.getBytes("US-ASCII"));
        response = br.readLine();
        command = "QUIT"+"\r\n";
        os.write(command.getBytes("US-ASCII"));
        response = br.readLine();
    }
        catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }    finally
    {
        if( socket != null )
        try {
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }       
         
            linkstatustring = "SENDED EMAIL";
            LinkStatus.setText(linkstatustring); 
            
            
            

        
        
    }//GEN-LAST:event_sendemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LinkStatus;
    private javax.swing.JPanel LinkStatusPanel;
    private javax.swing.JButton sendemail;
    // End of variables declaration//GEN-END:variables
}
